services:
  mongod_db:
    container_name: database_container
    image: mongo
    volumes:
      - mongo:/data/db
    ports:
      - 27012:27017
  app:
    build: .
    ports:
      - 4000:6000
    depends_on:
      - mongod_db
    env_file: ./.env
    environment:
      NODE_ENV: development
      PORT: 6000
      DATABASE_LOCAL: mongodb://mongod_db:27017/project?directConnection=true

volumes:
  mongo:
